repos:
  - repo: local
    hooks:
      - id: age-decision-api-fix
        name: age-decision-api-fix
        entry: ./scripts/ci/fix_all_docker.sh
        language: system
        pass_filenames: false
