services:
  age-decision-core:
    build:
      context: ../age-decision-core
      dockerfile: Dockerfile.dev
    networks:
      - age-decision-network

  age-decision-antispoof:
    build:
      context: ../age-decision-antispoof
      dockerfile: Dockerfile.dev
    networks:
      - age-decision-network

  age-decision-api:
    container_name: age-decision-api
    build:
      context: .
      dockerfile: ${AGE_DECISION_API_DOCKERFILE}
      args:
        VERSION: ${AGE_DECISION_API_VERSION}
        REPOSITORY: ${AGE_DECISION_API_REPOSITORY}
        TITLE: ${AGE_DECISION_API_TITLE}
        DESCRIPTION: ${AGE_DECISION_API_DESCRIPTION}
        LICENSE: ${AGE_DECISION_API_LICENSE}
    image: ${AGE_DECISION_API_IMAGE}:${AGE_DECISION_API_VERSION}
    ports:
      - "${APP_PORT}:8000"
    env_file:
      - .generated/runtime/dev.env
    volumes:
      - ./:/app
    depends_on:
      - age-decision-core
      - age-decision-antispoof
    restart: unless-stopped
    networks:
      - age-decision-network

networks:
  age-decision-network:
    name: age-decision-network
    driver: bridge
